"""add generic budgets to categories

Revision ID: 65164ae503f5
Revises: 358a0f126597
Create Date: 2026-08-08 18:26:32.841474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65164ae503f5'
down_revision: Union[str, Sequence[str], None] = '358a0f126597'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('default_budget_limit', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('categories', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'is_active')
    op.drop_column('categories', 'default_budget_limit')
    # ### end Alembic commands ###
